#!/bin/sh

if [ -e "/etc/config/ucitrack" ]; then
    uci -q batch <<-EOF
 		delete ucitrack.@passwall2[-1]
		add ucitrack passwall2
		set ucitrack.@passwall2[-1].init=passwall2
		delete ucitrack.@passwall2_server[-1]
		add ucitrack passwall2_server
		set ucitrack.@passwall2_server[-1].init=passwall2_server
		commit ucitrack
EOF
fi

uci -q batch <<-EOF
	delete firewall.passwall2
	set firewall.passwall2=include
	set firewall.passwall2.type='script'
	set firewall.passwall2.path='/var/etc/passwall2.include'

	delete firewall.passwall2_server
	set firewall.passwall2_server=include
	set firewall.passwall2_server.type='script'
	set firewall.passwall2_server.path='/var/etc/passwall2_server.include'

	set dhcp.@dnsmasq[0].localuse=1
	commit dhcp

	set uhttpd.main.max_requests=50
	commit uhttpd
EOF

if [ -x "/sbin/fw3" ]; then
	uci -q set firewall.passwall2.reload='1'
	uci -q set firewall.passwall2_server.reload='1'
else
	uci -q delete firewall.passwall2.reload
	uci -q delete firewall.passwall2.fw4_compatible
	uci -q delete firewall.passwall2_server.reload
	uci -q delete firewall.passwall2_server.fw4_compatible
fi
uci commit firewall


[ ! -s "/etc/config/passwall2" ] && cp -f /usr/share/passwall2/0_default_config /etc/config/passwall2

chmod +x /usr/share/passwall2/*.sh

[ "$(uci -q get passwall2.@global_xray[0].sniffing)" == "1" ] && [ "$(uci -q get passwall2.@global_xray[0].route_only)" != "1" ] && uci -q set passwall2.@global_xray[0].sniffing_override_dest=1
uci -q delete passwall2.@global_xray[0].sniffing
uci -q delete passwall2.@global_xray[0].route_only

for section in $(uci show passwall2 2>/dev/null | grep "\.add_from=" | cut -d'.' -f2); do
	old_val=$(uci -q get passwall2."${section}".add_from)
	if [ -n "$old_val" ]; then
		uci -q set passwall2."${section}".group="$old_val"
		uci -q delete passwall2."${section}".add_from
	fi
done

uci -q commit passwall2

rm -f /tmp/luci-indexcache /tmp/luci-indexcache.*
rm -rf /tmp/luci-modulecache/
killall -HUP rpcd 2>/dev/null

UPTIME=$(cut -d. -f1 /proc/uptime 2>/dev/null || echo 0)

if [ "$UPTIME" -gt 300 ]; then
	logger -t uci-defaults "Passwall2 live upgrade detected (Uptime: ${UPTIME}s). Marking..."
	(
#		sleep 3
		[ -x "/etc/init.d/passwall2" ] && /etc/init.d/passwall2 start >/dev/null 2>&1
#		[ -x "/etc/init.d/passwall2_server" ] && /etc/init.d/passwall2_server restart
	) &
else
	logger -t uci-defaults "Passwall2 first boot detected (Uptime: ${UPTIME}s). Skipping auto-restart to avoid boot loop."
fi

exit 0
