#
# Copyright (c) 2022-2023 SMALLPROGRAM <https://github.com/smallprogram>
# Description: Auto compile luci-app-passwall2
# Auto_compile_and_release.yml
name: "Auto compile with openwrt sdk"
permissions:
  contents: write
on:
  push:
    branches:
      - main
    paths:
      - '**/Makefile'
      - '!**/.github/**'
  repository_dispatch:
  workflow_dispatch:
  workflow_run:
    workflows: ["Sanitize Makefile"]
    types:
      - completed

env:
  TZ: Asia/Shanghai
  passwall2: ${{ github.repository }}
  packages: Jackie264/openwrt-passwall-packages
  GH_TOKEN_ORG: ${{ github.token }}

jobs:
  job_check:
    name: Check Version
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && github.event.head_commit.author.name != 'github-actions[bot]' && !contains(github.event.head_commit.message, 'Sync from xiaorouji')) ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    outputs:
      passwall2_version: ${{ steps.check_version.outputs.latest_version }}
      has_update: ${{ steps.check_version.outputs.has_update }}
      prerelease: ${{ steps.check_version.outputs.prerelease }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Check version
        id: check_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd luci-app-passwall2
          v=$(grep "^PKG_VERSION:=" Makefile | cut -d= -f2 | tr -d '[:space:]')
          r=$(grep "^PKG_RELEASE:=" Makefile | cut -d= -f2 | tr -d '[:space:]')
          latest_version="v${v}-r${r}"
          has_update=false
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "👋 Manual trigger detected, forcing build."
            has_update=true
          else
            if gh release view "$latest_version" --repo "${{ github.repository }}" > /dev/null 2>&1; then
              echo "⏭️ Version already exists in releases, skipping auto-build."
              has_update=false
            else
              has_update=true
            fi
          fi
          prerelease=$([ "${{ github.ref_name }}" == "main" ] && echo false || echo true)
          echo "latest_version=${latest_version}" >> $GITHUB_OUTPUT
          echo "has_update=${has_update}" >> $GITHUB_OUTPUT
          echo "prerelease=${prerelease}" >> $GITHUB_OUTPUT
          echo "Summary: Version=${latest_version}, HasUpdate=${has_update}, Prerelease=${prerelease}"

      - name: Prepare release
        if: steps.check_version.outputs.has_update == 'true'
        run: |
          echo "## :mega:Update content" >> release.txt
          echo "![](https://img.shields.io/github/downloads/${{ env.passwall2 }}/${{steps.check_version.outputs.latest_version}}/total?style=flat-square)" >> release.txt
          echo "### Passwall2 Info" >> release.txt
          echo "**:minidisc: Passwall2 Version: ${{steps.check_version.outputs.latest_version}}**" >> release.txt
          touch release.txt

      - name: Generate new tag & release
        if: steps.check_version.outputs.has_update == 'true'
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.check_version.outputs.latest_version}}
          make_latest: true
          target_commitish: ${{ github.ref_name }}
          prerelease: ${{steps.check_version.outputs.prerelease}}
          body_path: release.txt


  job_build_passwall2:
    name: Build for ${{ matrix.ow_ver }} / ${{ matrix.ext }}
    needs: job_check
    if: needs.job_check.outputs.has_update == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ow_ver: "24.10"
            sdk_url: "https://downloads.openwrt.org/releases/24.10.6/targets/x86/64/openwrt-sdk-24.10.6-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst"
            ext: "ipk"
          - ow_ver: "25.12"
            sdk_url: "https://downloads.openwrt.org/releases/25.12.4/targets/x86/64/openwrt-sdk-25.12.4-x86-64_gcc-14.3.0_musl.Linux-x86_64.tar.zst"
            ext: "apk"

    steps:
      - name: Install packages
        run: |
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android
          echo "Install packages"
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
            bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
            g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
            libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
            libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
            ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
            python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
            upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Cache OpenWrt dl
        uses: actions/cache@v5
        with:
          path: sdk/dl
          key: ${{ runner.os }}-openwrt-dl-${{ matrix.ow_ver }}-${{ hashFiles('**/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-openwrt-dl-${{ matrix.ow_ver }}-

      - name: Initialization SDK
        run: |
          wget -q ${{ matrix.sdk_url }} -O sdk.tar.zst
          mkdir -p sdk
          tar --zstd -x -f sdk.tar.zst -C ./sdk --strip-components=1
          cd sdk

          cat > feeds.conf.default << EOF
          src-git passwall2 https://github.com/${{ env.passwall2 }}.git;${{ github.ref_name }}
          src-git base https://github.com/openwrt/openwrt.git;openwrt-${{ matrix.ow_ver }}
          src-git packages https://github.com/openwrt/packages.git;openwrt-${{ matrix.ow_ver }}
          src-git luci https://github.com/openwrt/luci.git;openwrt-${{ matrix.ow_ver }}
          src-git routing https://github.com/openwrt/routing.git;openwrt-${{ matrix.ow_ver }}
          src-git telephony https://github.com/openwrt/telephony.git;openwrt-${{ matrix.ow_ver }}
          EOF
          
          ./scripts/feeds update -a
          ./scripts/feeds install -a

          #--------------------------------------begin_patches------------------------------------------
          echo "Start applying the patch"

          rm -rf temp_resp
          git clone -b master --single-branch https://github.com/openwrt/packages.git temp_resp
          echo "update golang version"
          rm -rf feeds/packages/lang/golang
          cp -r temp_resp/lang/golang feeds/packages/lang
          echo "update rust version"
          rm -rf feeds/packages/lang/rust
          cp -r temp_resp/lang/rust feeds/packages/lang
          rm -rf temp_resp

          echo "update patch-kernel.sh"
          git clone -b main --single-branch https://github.com/openwrt/openwrt.git temp_resp
          cp -f temp_resp/scripts/patch-kernel.sh scripts/
          rm -rf temp_resp

          echo "Patch application completed"
          #--------------------------------------end_patches--------------------------------------------

      - name: Compile passwall2
        id: compile
        run: |
          cd sdk
          echo "CONFIG_ALL_NONSHARED=n" > .config
          echo "CONFIG_ALL_KMODS=n" >> .config
          echo "CONFIG_ALL=n" >> .config
          echo "CONFIG_AUTOREMOVE=n" >> .config
          echo "CONFIG_PACKAGE_luci-app-passwall2=m" >> .config
          make defconfig
          echo "make package/luci-app-passwall2/{clean,compile} -j$(nproc)"
          make package/luci-app-passwall2/{clean,compile} -j$(nproc) V=s
          mkdir -p ../artifacts
          find bin/packages/ -type f -name "*passwall2*.${{ matrix.ext }}" -exec cp {} ../artifacts/ \;
          make clean
          rm .config .config.old
          rm -rf feeds/passwall2 feeds/passwall2.*
          cd ..
          echo "status=success" >> $GITHUB_OUTPUT

      - name: 📦 Upload build artifact
        if: steps.compile.outputs.status == 'success'
        uses: actions/upload-artifact@v7
        with:
          name: passwall2-artifacts-${{ matrix.ow_ver }}
          path: artifacts/*.${{ matrix.ext }}
          if-no-files-found: error

  job_release:
    name: 3. Release & Deploy
    needs: [job_check, job_build_passwall2]
    if: needs.job_check.outputs.has_update == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v7

      - name: ⬇️ Download all build artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: passwall2-artifacts-*
          path: ./release-assets
          merge-multiple: true

      - name: 📝 Prepare release text
        run: |
          echo "## :mega:Update content" >> release.txt
          echo "![](https://img.shields.io/github/downloads/${{ github.repository }}/${{ needs.job_check.outputs.passwall2_version }}/total?style=flat-square)" >> release.txt
          echo "### Passwall2 Info" >> release.txt
          echo "**:minidisc: Passwall2 Version: ${{ needs.job_check.outputs.passwall2_version }}**" >> release.txt

      - name: 🗃️ Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.job_check.outputs.passwall2_version }}
          make_latest: true
          target_commitish: ${{ github.ref_name }}
          prerelease: ${{ needs.job_check.outputs.prerelease == 'true' }}
          body_path: release.txt
          files: |
            ./release-assets/*.ipk
            ./release-assets/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔑 Checkout custom-packages repo
        uses: actions/checkout@v7
        with:
          # repository: OneNAS-space/custom-packages
          repository: SwrodKing/custom-packages_onenas
          token: ${{ secrets.CUSTOM_PACKAGES_TOKEN }}
          path: custom-packages

      - name: 🚚 Update luci artifacts
        run: |
          set -e
          CURRENT_PKG="luci-app-passwall2"
          mkdir -p custom-packages/releases/packages-24.10/luci
          mkdir -p custom-packages/releases/packages-25.12/luci
          
          echo "Cleaning all old versions for $CURRENT_PKG before updating..."
          rm -f custom-packages/releases/packages-24.10/luci/${CURRENT_PKG}_*.ipk
          rm -f custom-packages/releases/packages-25.12/luci/${CURRENT_PKG}-*.apk
          
          find ./release-assets -type f \( -name "*.ipk" -o -name "*.apk" \) | while read -r f; do
            base=$(basename "$f")
            if [[ "$base" == *.ipk ]]; then
              echo "Deploying $base to releases/packages-24.10/luci/"
              cp "$f" custom-packages/releases/packages-24.10/luci/
            elif [[ "$base" == *.apk ]]; then
              echo "Deploying $base to releases/packages-25.12/luci/"
              cp "$f" custom-packages/releases/packages-25.12/luci/
            fi
          done
          
          echo "=== 24.10 Content ==="
          ls -la custom-packages/releases/packages-24.10/luci/${CURRENT_PKG}* || echo "No IPKs found"
          echo "=== 25.12 Content ==="
          ls -la custom-packages/releases/packages-25.12/luci/${CURRENT_PKG}* || echo "No APKs found"

          cd custom-packages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add releases/packages-24.10/luci/ releases/packages-25.12/luci/
          
          if git diff --staged --quiet; then
            echo "按兵不动：没有检测到文件变化，跳过提交。"
          else
            git commit -m "Update $CURRENT_PKG to ${{ needs.job_check.outputs.passwall2_version }}"
            for i in {1..5}; do
              git pull --rebase origin main && \
              git push origin main && break || \
              (echo "Conflict detected, retrying in 5s..." && sleep 5)
            done
          fi